services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_root_password
      - db_password
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    secrets:
      - db_password
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress

  # Bonus services
  redis:
    container_name: redis
    build: 
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:inception
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - inception_network
    restart: unless-stopped
    expose:
      - "6379"

  ftp:
    container_name: ftp
    build: 
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp:inception
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - wordpress_data:/var/ftp/wordpress
    networks:
      - inception_network
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: unless-stopped

  adminer:
    container_name: adminer
    build: 
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:inception
    networks:
      - inception_network
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mariadb

  static-site:
    container_name: static-site
    build: 
      context: ./requirements/bonus/static-site
      dockerfile: Dockerfile
    image: static-site:inception
    networks:
      - inception_network
    ports:
      - "8081:80"
    restart: unless-stopped

  portainer:
    container_name: portainer
    build: 
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    image: portainer:inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_network
    ports:
      - "9443:9443"
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/redis
  portainer_data:
    driver: local

networks:
  inception_network:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
